WIP Subrecords EEE TTT
EEE mel_type
EEE docs return None from pack subrecords data
EEE MelUInt32('INDX', '')
EEE and header.label not in {'CELL','WRLD'}:
EEE
@@ -525,3 +525,3 @@ def __init__(self, mel_sig, attr, default=None, maxSize=0):
         self.maxSize = maxSize
-        self.encoding = None # None == automatic detection
+        self.encoding = None # will default to bolt.pluginEncoding

A dream come True. There is too much goodness in here so some random
notes:

- dumpData overrides went down. Now we actually override the part of the
behavior we need - we can further centralize/optimize etc
- ModWritter is gone - another level of function calls, another API for
new (and seasoned) devs to grok, and most importantly packing/loading
logic all around the place
- strings handling is centralized - defining packSub0 and co away from
the usages was difficult to follow. Plus this is a part of the code that
needs work - note discoveries on decode performance, the encodings
handling/naming is difficult to follow and rework for py3 plus cstrip
must disappear
- packSub does not do this weird "call me in two ways" - this is handled
by pack_subrecord_data
- used some itertools and comprehensions to avoid copying data, drop
inlines etc. I did use some `map`s here
- note _collect_array_data was already pack_subrecord_data - we now don't
need the sio however :) Plus to me it's much easier to reason about a
function than to reason about the stream that I write on - seeing:

-    def _collect_array_data(self, record):
+    def pack_subrecord_data(self, record):
         """Collects the actual data that will be dumped out."""
-        array_data = MelArray._DirectModWriter(sio())
-        if self._prelude:
-            self._prelude.dumpData(record, array_data)

I already wonder how come dumpData does not write headers in line 3 -
cause the definition of _DirectModWriter two lines above does not help
much. All this is past - now functions do one thing - only real
complication is the strings one - the packSub0 (sic) is replaced with
_dump_bytes and package_subrecord_data - was doing too much (actually
data was always encoded (see usages) no need for if checks) and too
little (copy/pasting packSub and buggily at that) TTTTT
- subType -> mel_sig
- I threw slots in but don't feel we should go and slot all subclasses -
this is still WIP
- subrecords attribute removed from MelRecord, making all instances
lighter - more to follow

limits are things like:

MelUInt32('INDX', '').packSub(out, struct_pack(u'=I', part_attr))

although I still find this more readable - would like to absorb the
packing in there. The attr being '' (EEE rename to u'unused') is
just exposing our current model a bit too bluntly: records are *not*
composed of MelBase instances - those just set/dump the attributes of
the records passed in from/to the stream they are passed in. I guess this
was done to save memory and it's probably a good idea - but defining the
records as sets of MelBase instances might also be a good idea - that's
pt4

_MelSimpleStruct(MelStruct) -> _MelSimpleStruct(MelBase) TTT

get rid of quite a few processing - I may have missed some needed override

Mopy/bash/brec/basic_elements.py: avoid concatenating strings

packSub0 call self.packSub TTT

I don't want to copy data so this is XXX but note:

- if data is None: was never (see also rewrite later)
- data was always encoded (see usages) no need for if checks
- comparison was wrong? if lenData < 0xFFFF: is if lenData <= 0xFFFF:
in packSub TTT
- note subheader format is hardcoded

SSS runs! BP crashes EEE

Traceback (most recent call last):
  File "bash\gui\events.py", line 166, in _post
    result = listener(*listener_args)
  File "bash\balt.py", line 904, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\patcher_dialog.py", line 190, in PatchExecute
    patchFile.init_patchers_data(enabled_patchers, SubProgress(progress, 0, 0.1)) #try to speed this up!
  File "bash\patcher\patch_files.py", line 167, in init_patchers_data
    patcher.initData(SubProgress(progress, index))
  File "bash\patcher\patchers\importers.py", line 707, in initData
    record):
  File "bash\bolt.py", line 902, in __eq__
    return self._cs == Path.__getCase(other)
  File "bash\bolt.py", line 433, in __getCase
    return os.path.normcase(os.path.normpath(name))
  File "C:\Users\MrD\venvs\wrye-wx4-win\lib\ntpath.py", line 419, in normpath
    if path.startswith(('\\\\.\\', '\\\\?\\')):
AttributeError: 'int' object has no attribute 'startswith'

Turns out:

<DABoethiaChosen09 [NPC_:(Oblivion.esm, 0A2AE5)]>

combatStyle = (bolt.Path(u'Oblivion.esm'), 0)

So we were not expecting a long fid?
I chose a bit arcane mel_sig cause sub_rec_sig was too verbose and because
code already thinks in terms of "mod elements". It's searchable and should
be confined to current uses

_MelField/MelStruct._packer

less function calls and more local scope, but importantly stop thinking
in terms of format and think in terms of operations. struct_pack uses are
a nice metric (less is better :P)

FFF skip group

squash!     WIP Subrecords EEE TTT